config/routes.rb
TutoRails::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
    
  root :to => 'pages#home'
  match '/show/:id'       =>  'users#show',       :as => :show,         via:'get'
  match '/signup'         =>  'users#new',        :as => :signup,       via:'get'
  match '/signin'         =>  'sessions#new',     :as => :signin,       via:'get'
  match '/signout'        =>  'sessions#destroy', :as => :signout,      via:'delete'
  match '/about'          =>  'pages#about',      :as => :about,        via:'get'
  match '/contact'        =>  'pages#contact',    :as => :contact,      via:'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :pseudo, :password, :password_confirmation
  
  #require init of remember_token
  before_create :create_remember_token
  
  #store pseudos & emails in downcase
  before_save { self.pseudo = pseudo.downcase }
  before_save { self.email = email.downcase }
  
  validates :pseudo, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  
  validates :password, presence: true, length: { minimum: 5 }
  validates :password_confirmation, presence: true, length: { minimum: 5 }
  
  has_secure_password
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end  
  
  private
  
  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by_email(params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            sign_in user
            redirect_to user
        else
            flash.now[:danger] = 'Invalid email/password'
            render 'new'
        end
        
    end
    
    def destroy
        sign_out
        redirect_to :root
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:success] = "Welcome there !"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.all
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      render 'edit'
    end
  end  

  private
    def user_params
      params.require(:user).permit(:pseudo, :email, :password, :password_confirmation)
    end
    
    def signed_in_user
      deny_access("Please sign in !", :signin) unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:id])
      deny_access("Cannot edit other users profile !", root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Return a title on a per-page basis.
    def title
        base_title = "Tuto RoR"
        if @title.nil?
           base_title
        else
           "#{base_title} | #{@title}"
        end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
       remember_token = User.new_remember_token
       cookies.permanent[:remember_token] = remember_token
       user.update_attribute(:remember_token, User.digest(remember_token))
       self.current_user = user
    end
    
    def sign_out
        cookies.delete(:remember_token)
        self.current_user = nil
    end
    
    def signed_in?
        !current_user.nil?
    end
    
    def current_user=(user)
        @current_user = user
    end
    
    def current_user?(user)
        @current_user == user
    end
    
    def current_user
       remember_token = User.digest(cookies[:remember_token])
       @current_user ||= User.find_by_remember_token(remember_token)
    end
    
    def deny_access(msg, relocate_to)
        flash[:warning] = msg
        redirect_to relocate_to
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="well well-sm">
        Done with Ruby on Rails by <a href="http://www.celine-liberal.fr">Céline Libéral</a>
    </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Tutot RoR</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", :root %></li>
        <li><%= link_to "About", :about %></li>
        <li><%= link_to "Our community", users_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">User menu<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Public profile", current_user %></li>
              <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", :signout, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in / Sign up", :signin %></li>
        <% end %>
        <li><%= link_to "Contact", :contact %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Celisoft">
  
  <title><%= title %></title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-dismissible alert-<%= key %>">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        </button>
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <h2>About</h2>
    <p>
      42 ?
    </p>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
    <h2>Contact</h2>
    <p>
        Please contact Dr Who instead of me.
    </p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
    <h2>Home</h2>
    <p>
      Welcome on the homepage. Hope you will enjoy my useless RoR application.
    </p>
    <%= link_to "Sign up now!", :signup, class: "btn btn-large btn-primary" %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-warning" role="alert">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="jumbotron">
    <div class="signup_form center-block">
            <h2>Update your profile</h2>
            <%= form_for(@user) do |f| %>
              <%= render 'shared/error_messages' %>
              <div class="input-group">
                  <%= f.label :pseudo, class: "input-group-addon" %>
                  <%= f.text_field :pseudo, class: "form-control", placeholder: "Username" %>
              </div>
              <br />
              <div class="input-group">
                  <%= f.label :email, class: "input-group-addon" %>
                  <%= f.text_field :email, class: "form-control", placeholder: "Email address" %>
              </div>
              <br />
              <div class="input-group">
                  <%= f.label :password, class: "input-group-addon" %>
                  <%= f.password_field :password, class: "form-control" %>
              </div>
              <br />
              <div class="input-group">
                  <%= f.label :password_confirmation, "Confirmation", class: "input-group-addon" %>
                  <%= f.password_field :password_confirmation, class: "form-control" %>
              </div>
              <br />
              <%= f.submit "Update", class: "btn btn-large btn-primary" %>
            <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
    <h2>Community members</h2>
    <p>
        Here is the list of our members.
    </p>
    <ul>
        <% @users.each do |user| %>
          <li><%= link_to user.pseudo, user %></li>
        <% end %>
    </ul>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
    <div class="signup_form center-block">
            <h2>Signing up</h2>
            <p>
                You're here because you want to sign up to my wonderful useless RoR application.
                
                Here's some information we need to create your account:
            </p>
            <%= form_for(@user) do |f| %>
              <%= render 'shared/error_messages' %>
              <div class="input-group">
                  <%= f.label :pseudo, class: "input-group-addon" %>
                  <%= f.text_field :pseudo, class: "form-control", placeholder: "Username" %>
              </div>
              <br />
              <div class="input-group">
                  <%= f.label :email, class: "input-group-addon" %>
                  <%= f.text_field :email, class: "form-control", placeholder: "Email address" %>
              </div>
              <br />
              <div class="input-group">
                  <%= f.label :password, class: "input-group-addon" %>
                  <%= f.password_field :password, class: "form-control" %>
              </div>
              <br />
              <div class="input-group">
                  <%= f.label :password_confirmation, "Confirmation", class: "input-group-addon" %>
                  <%= f.password_field :password_confirmation, class: "form-control" %>
              </div>
              <br />
              <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
            <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
    <h2>Profile for [ <%= @user.pseudo %>]</h2>
    <p>
        <ul>
            <li>Username : <%= @user.pseudo %></li>
            <li>Mail address: <%= @user.email %></li>
        </ul>
    </p>
</div>